#!/bin/bash

## Description: Install all TYPO3 versions with t3_cowriter extension
## Usage: install-all
## Example: ddev install-all

set -e

echo "=== Installing all TYPO3 versions ==="
echo ""

# For v4.0.0, only TYPO3 v14 is installed by default (v13.4 also supported)
/mnt/ddev_config/commands/web/install-v14

echo ""
echo "=== All installations complete ==="
echo ""
echo "Available environments:"
echo "  - TYPO3 v14: https://v14.${DDEV_HOSTNAME}/typo3/"
echo ""
echo "Login: admin / Joh316!!"
