#!/bin/bash

## Description: Install all TYPO3 versions with t3_cowriter extension
## Usage: install-all
## Example: ddev install-all

set -e

echo "=== Installing all TYPO3 versions ==="
echo ""

/mnt/ddev_config/commands/web/install-v13
echo ""
/mnt/ddev_config/commands/web/install-v14

echo ""
echo "=== All installations complete ==="
echo ""
echo "Available environments:"
echo "  - TYPO3 v13: https://v13.${DDEV_SITENAME}.ddev.site/typo3/"
echo "  - TYPO3 v14: https://v14.${DDEV_SITENAME}.ddev.site/typo3/"
echo ""
echo "Login: admin / Joh316!!"
